name: Deploy to Heroku

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              env:
                  NODE_ENV: production
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}
                  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
                  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
                  AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
                  AUTH0_CALLBACK_URL: ${{ secrets.AUTH0_CALLBACK_URL }}
                  AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
                  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
                  DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
                  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
                  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
                  EMAIL_USER: ${{ secrets.EMAIL_USER }}
                  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
                  STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
                  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
              run: npm test

            - name: Build application
              env:
                  NODE_ENV: production
              run: npm run build

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                  heroku_app_name: 'vinylapp'
                  heroku_email: ${{ secrets.HEROKU_EMAIL }}
